when@dev:
    _errors:
        resource: "@FrameworkBundle/Resources/config/routing/errors.php"
        prefix: /_error

framework:
    trusted_proxies: "%env(TRUSTED_PROXIES)%"
    trusted_headers:
        [
            "x-forwarded-for",
            "x-forwarded-host",
            "x-forwarded-proto",
            "x-forwarded-port",
            "x-forwarded-prefix",
        ]
